export default [
  {label: 'Dollar ($)', value: 'en-US/USD'},
  {label: 'Euro (€)', value: 'de-DE/EUR'},
  {label: 'Pound (£)', value: 'en-GB/GBP'},
  {label: 'Yen (¥)', value: 'ja-JP/JPY'},
  {label: 'Yuan (¥)', value: 'zh-CN/CNY'},
  {label: 'Rupee (₹)', value: 'en-IN/INR'},
  {label: 'Real (R$)', value: 'pt-BR/BRL'},
  {label: 'Won (₩)', value: 'ko-KR/KRW'},
  {label: 'Franc (CHF)', value: 'de-CH/CHF'},
  {label: 'Krona/Krone (kr)', value: 'sv-SE/SEK'},
  {label: 'Rubles (₽)', value: 'ru-RU/RUB'},
  {label: 'Rand (R)', value: 'en-ZA/ZAR'},
  {label: 'Zloty (zł)', value: 'pl-PL/PLN'},
  {label: 'Lira (₺)', value: 'tr-TR/TRY'},
  {label: 'Shekel (₪)', value: 'he-IL/ILS'},
  {label: 'Baht (฿)', value: 'th-TH/THB'},
  {label: 'Peso (₱)', value: 'fil-PH/PHP'},
  {label: 'Ringgit (RM)', value: 'ms-MY/MYR'},
  {label: 'Rupiah (Rp)', value: 'id-ID/IDR'},
  {label: 'Dong (₫)', value: 'vi-VN/VND'},
];
